- name: fedora version is identified
  set_fact:
    fedora_version: "{{ ansible_distribution_major_version }}"

- name: existence of rpmfusion (free) is checked
  stat:
    path: /etc/yum.repos.d/rpmfusion-free.repo
  register: check_rpmfusion_free

- name: existence of rpmfusion (nonfree) is checked
  stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree.repo
  register: check_rpmfusion_nonfree

- name: rpm fusion (free) is enabled
  yum:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
    state: present
  when: not check_rpmfusion_free.stat.exists

- name: rpm fusion (nonfree) is enabled
  yum:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
    state: present
  when: not check_rpmfusion_nonfree.stat.exists
